include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    use_build_context_synchronously: true
    always_declare_return_types: true
    annotate_overrides: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    empty_catches: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: true
    unnecessary_this: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
